### ISSUE TITLE
how files are decrypted

### ISSUE THREAD

**Issue by Mrcosta20** [DestroyerDarkNess/Shareware-Ransomware#1]
how files are decrypted thanks

**Comment by DestroyerDarkNess** [comment]
I have not had the time to complete it, its operation has been explained in this Post:
[https://foro.elhacker.net/abril_negro/abril_negro_2020_shareware_ransomware-t504255.0.html](https://foro.elhacker.net/abril_negro/abril_negro_2020_shareware_ransomware-t504255.0.html)

**Comment by DestroyerDarkNess** [comment]
Decryptor was added, and major changes were made to the encryption mode and method.
